[build]
command = "npm run build:ssr && npm run compile:function"
publish = "dist/website/browser"
functions = "netlify/functions"

[[redirects]]
from = "/*"
to = "/.netlify/functions/ssr"
status = 200
